Fixed an issue where a Republish Fallback Action could fail with the following error when the originating rule SQL didn't include the `metadata` field from rule environment.

```
[error] tag: RESOURCE, msg: failed_to_trigger_fallback_action, reason: {error,function_clause}, fallback_kind: republish, primary_action_resource_id: <<"action:type:name:connector:type:name">>, republish_topic: <<"republish/topic">>
```
